### ISSUE TITLE
[NUXE-654] React Typeahead: clear selected option after selecting an option 

### ISSUE THREAD

**Issue by stevelandwehr** [powerhome/playbook#1397] opened 2021-03-18 15:10 UTC
**Is your feature request related to a problem? Please describe.**
After making a selection in the React Typeahead kit, the user needs to click the "x" icon to clear the selected option in order to start typing in the text box again. 

**Describe the solution you'd like**
After making a selection in the React Typeahead kit, clear out the selected option so the user can start typing in the text box again.

**Additional context**
https://nitro.powerhrg.com/runway/backlog_items/BOP-380

**Comment by kevinschlabach** [comment] 2021-03-18 15:24
To elaborate on this experience context, in Runway we have a team members listing page (under team settings) and the user runs a search for another nitro user and upon mouse click or enter, that user is submitted into the list below (but not saved until the explicit form's saves button is clicked)... in this scenario, the user remains in the form field until the user manually clears it.  This confuses the user since they should be able to perform another search, but this not visually obvious.

We had this same issue on the runway reviewers search form, but that version was in Rails and we were able to add javascript locally to clear it.  That kit version could also use this enhancement.

All that being said, there are other places in Nitro that might not want this, so it should be a property/option of some sort.

**Comment by thestephenmarshall** [comment] 2021-05-04 16:36
Confirmed. Runway ticket https://nitro.powerhrg.com/runway/backlog_items/NUXE-654 has been created. This story will be added in an upcoming sprint.

**Comment by co1in-1ewis** [comment] 2023-05-25 20:00
Closing this issue in favor of [PLAY-78](https://nitro.powerhrg.com/runway/backlog_items/PLAY-78).

**Closed by co1in-1ewis** 2023-05-25 20:00 UTC
Labels: feature request
