### ISSUE TITLE
User Kit Avatars

### ISSUE THREAD

**Issue by roxannecojocariu** [powerhome/playbook#1031] opened 2020-08-25 18:32 UTC
**Describe the bug**
User kit avatar is not loading consistently

**To Reproduce**
1. Go to [the corporate directory](https://nitro.powerhrg.com/directory)
2. Type someone's name into user typeahead search
3. See avatar flicker and then disappear

**Expected behavior**
Avatar should not disappear

**Screenshots**
Even better, here's a video: 
[avatar_bug.zip](https://github.com/powerhome/playbook/files/5125590/avatar_bug.zip)

**Additional context**
We have a hypothesis that it may have to do with a conflict between the lazy load library being used for avatars and the image's `src` being injected into the DOM asynchronously. I could be totally wrong here, but it seems like there is some sort of conflict as the avatar kit seems to render fine when we're not injecting the image's `src` into the DOM

**Comment by thestephenmarshall** [comment] 2020-08-25 19:59
Thanks for adding the info for this bug. The image requests are being cancelled, so my theory is that the menu js itself is schizophrenic and simply needs some delay added.

**Comment by jasoncypret** [comment] 2020-08-28 16:53
Linked: https://nitro.powerhrg.com/runway/backlog_items/NUX-1380

**Comment by thestephenmarshall** [comment] 2020-10-15 14:21
The docs have been fixed in Playbook and a PR is [opened for Nitro](https://github.com/powerhome/nitro-web/pull/17368). Summary: we should never be calling `setAttribute('src', user.avatar_url)`, but instead do this `dataset.src = user.avatar_url`. This allows `lazy-sizes` to work as intended.

**Closed** 2020-10-15 14:21 UTC
Labels: bug, confirmed
