### ISSUE TITLE
Inline select background

### ISSUE THREAD

**Issue by haydenrou** [powerhome/playbook#1597] opened 2021-08-26 14:10 UTC
**Describe the bug**
There is a feint hover on the inline select kit whilst it's focused until you click off

**Screenshots**
<img width="765" alt="Screenshot 2021-08-26 at 7 08 53 AM" src="https://user-images.githubusercontent.com/21108297/130978150-9dded2a1-50b8-40de-ba81-06339f43fee9.png">

Noted by Eva & Hayden

**Comment by jasoncypret** [comment] 2021-09-08 14:02
Upon closer inspection this IS NOT a bug. It is the focused state. For selects the focus remains after making a selection. We might consider changing the focus state to include an outline...but we need the designers to look at that

**Comment by haydenrou** [comment] 2021-09-20 17:48
I created this after a conversation with @evalouderback where the outcome was that we thought it was a bug. Just to confirm this is not me "feature requesting" that this is removed, I just said I'd raise it. If it's not a bug you could close the issue unless you plan on changing it.

**Comment by co1in-1ewis** [comment] 2023-05-26 13:48
Closing and moving to [PLAY-852](https://nitro.powerhrg.com/runway/backlog_items/PLAY-852) for follow-up.

**Closed by co1in-1ewis** 2023-05-26 13:48 UTC
Labels: feature request, Needs Runway, Needs Design
